---
title: "SST1 plots"
author: "G$"
date: "9/3/2020"
output: pdf_document
---

---
```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(knitr)
library(tidyverse)
library(bsseq)
library(Biostrings)
library(ggplot2)
library(png)
library(cowplot)
options(scipen=999)
library(zoo)
options(knitr.duplicate.label = 'allow')
source("/home/isac/Code/ilee/plot/ilee_plot_utils.R")
library("ggsci")
source("/home/isac/Code/nanopore-methylation-utilities/methylation_R_utils.R")
```

```{r}
figs="/kyber/Data/Nanopore/Analysis/gmoney/CHM13/v1.0_final_assembly/TE/figures"
dat="/kyber/Data/Nanopore/Analysis/gmoney/CHM13/v1.0_final_assembly"

sst1_meth <- read_tsv(paste0(dat, "/TE/t2t_chm13v1.0_SST1_methylated.bed"))
sst1_unmeth <- read_tsv(paste0(dat, "/TE/t2t_chm13v1.0_SST1_unmethylated.bed"))
sst1 <- rbind(sst1_meth, sst1_unmeth) %>%
  filter(len > 1290) %>%
  group_by(chr) %>%
  filter(n() > 10)


repstats <- read_csv(paste0(dat, "/TE/SST1_methyl-unmethyl_combinedStats--all--species.csv"))


violin <- ggplot(data = sst1, aes(y = factor(chr), x = avgmeth, fill = clust_meth))+geom_density_ridges(rel_min_height = 0.01,scale = 0.9,quantile_lines = TRUE, quantiles = 2, bandwidth = .025)+theme_classic(base_size = 20)+labs(x = "Methylation", y = "Repeat")

```

```{r}
chrom.sizes <- read_tsv(paste0(dat, "/reference/chrom.sizes"), col_names = F)
cen <- as.data.frame(censat.gr) %>%
  select(-c("strand", "name"))

colnames(chrom.sizes) <- c("chromosome", "size")
colnames(cen) <- c("chromosome", "start", "end", "width")

chrom_order <- c("chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", 
                 "chr8", "chr9", "chr10", "chr11", "chr12", "chr13", "chr14", 
                 "chr15", "chr16", "chr17", "chr18", "chr19", "chr20", "chr21", 
                 "chr22", "chrX")
chrom_key <- setNames(object = as.character(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 
                                              12, 13, 14, 15, 16, 17, 18, 19, 20, 
                                              21, 22, 23)), 
                      nm = chrom_order)
chrom_order <- factor(x = chrom_order, levels = rev(chrom_order))

# convert the chromosome column in each dataset to the ordered factor
chrom.sizes[["chromosome"]] <- factor(x = chrom.sizes[["chromosome"]], 
                                      levels = chrom_order)
cen[["chromosome"]] <- factor(x = cen[["chromosome"]], 
                                      levels = chrom_order)

sst1[["chr"]] <- factor(x = sst1[["chr"]], 
                                     levels = chrom_order)

plot <- ggplot(data = chrom.sizes) + 
    # base rectangles for the chroms, with numeric value for each chrom on the x-axis
    geom_rect(aes(xmin = as.numeric(chromosome) - 0.2, 
                  xmax = as.numeric(chromosome) + 0.2, 
                  ymax = size, ymin = 0), 
              colour="black", fill = "white") + 
    # rotate the plot 90 degrees
    coord_flip() +
    # black & white color theme 
    theme(axis.text.x = element_text(colour = "black"), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          panel.background = element_blank()) + 
    # give the appearance of a discrete axis with chrom labels
    scale_x_discrete(name = "chromosome", limits = names(chrom_key)) +
    # add bands for centromeres
    geom_rect(data = cen, aes(xmin = as.numeric(chromosome) - 0.2, 
                                      xmax = as.numeric(chromosome) + 0.2, 
                                      ymax = end, ymin = start, alpha = .5)) +
    # add bands for CNA value
    geom_rect(data = sst1, aes(xmin = as.numeric(chr) - 0.2, 
                                     xmax = as.numeric(chr) + 0.2, 
                                     ymax = end, ymin = start, fill = avgmeth)) + 
    scale_fill_gradient(low = "blue", high = "red") 

```

