---
title: "`r params$newtitle`"
output: pdf_document

---
```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(knitr)
library(tidyverse)
library(bsseq)
library(Biostrings)
library(ggplot2)
library(png)
library(cowplot)
options(scipen=999)
options(knitr.duplicate.label = 'allow')
```



```{r include=FALSE}
tig=params$tig
size <- read_tsv(params$size, col_names = F)
size = size$X2

if (size <= 1000000){
  cen1=1} else if (params$cen1 >= 10000){
  cen1=(params$cen1)-10000
  }else{
    cen1=params$cen1}

if (size <= 1000000){
  cen2 = size} else if ((params$cen2+10000) >= size){
  cen2=(params$cen2)
}else{
    cen2=params$cen2+10000
  }

bismark <- read_tsv(params$bismark, col_names = F)
cov <- read_tsv(params$cov, col_names = F)
BS <- read.bismark(params$bismark)




repeats <- read_tsv(params$repeats, col_names = F) %>%
  mutate(X2 = (X2-1)) %>%
  separate(X5, c("class", "family"), sep =  "/") %>%
  mutate("family" = replace_na(family, "Unknown")) %>%
  rename(X4 = "repeat_type") %>%
  mutate(name = ifelse(family == c("centr"), paste0(class,"/",family),class)) %>%
  mutate(name = ifelse(family == c("telo"), paste0(class,"/",family),name)) %>%
  mutate(name = ifelse(family == c("acro"), paste0(class,"/",family),name)) %>%
  mutate(name = ifelse(family == c("subtelo"), paste0(class,"/",family),name)) %>%
  mutate(name = ifelse(name == c("Satellite"), repeat_type,name)) %>%
  mutate(name = ifelse(name == "Satellite/centr", repeat_type, name)) %>%
  mutate(name = ifelse(name == "DNA?", "DNA", name)) %>%
  mutate(name = ifelse(grepl("GSAT", repeat_type), "GSAT", name)) %>%
  mutate(name = ifelse(grepl("HSAT", repeat_type), "HSAT", name)) %>%
  mutate(name = ifelse(name == "Unspecified", "Unknown", name)) %>%
  mutate(name = ifelse(class == c("RC"), paste0(class,"/",family),name)) %>%
  mutate(name = as.factor(name))

```

```{r include = FALSE}

if (cen2-cen1 <= 50000){
  smoothed=10
}else if (cen2-cen1 <= 100000){
    smoothed=50
}else{
  smoothed = 500
}



smooth <-BSmooth(BS, 
                 ns=smoothed)

rawmeth <- getMeth(BS, type = "raw")
getmeth <- getMeth(smooth)
getmeth <- as_tibble(cbind(getmeth, bismark$X2), colnames(c("meth", "coords")))

rawmeth <- as_tibble(cbind(bismark$X1, bismark$X2, rawmeth))
rawmeth <- add_column(rawmeth, d = "meth", .after = 2)

#write.table(rawmeth, file = paste0("/uru/Data/Nanopore/Analysis/gmoney/chm13/censat/phase_2/wig/",tig, ".wig"), col.names = F, row.names = F, quote = F, sep = "\t")
colnames(getmeth) <- c("meth", "coord")

cpgs <- getmeth %>%
  filter(coord >= cen1) %>%
  filter(coord <= cen2)

total_cpg <- length(cpgs$coord)


```



Methylation data for:  `r params$tig`:
`r params$cen1`-
`r params$cen2`

Methylation smooth: `r smoothed` nucleotides

`r total_cpg` CpG sites in `r cen2-cen1` nucleotides

`r total_cpg/((cen2-cen1)/1000)` CpGs per 1Kb 

```{r fig.width=12, fig.height=6}
plot <- getmeth %>% 
  ggplot(aes(x = (coord), y= meth)) +geom_line()+ labs(x="Genomic coordinates (Mb)", y="Methylation")+theme_bw(base_size = 25)+xlim(cen1,cen2)

```


```{r fig.width=12, fig.height=6}
depth <- ggplot(cov, aes(x=X2, y=X4))+geom_line()+ labs(x="Genomic coordinates (Mb)", y="read depth")+theme_bw(base_size = 25)+xlim(cen1,cen2)

```



```{r fig.width=12, fig.height=10}



    
repeatColors =c("(CATTC)n" = "#E87C71",
    "(GAATC)n"="#E28455",
    "ALR/Alpha"="#D78C32",
    "BSR/Beta"="#E370AB",
    "CER" = "#CE9334",
    "DNA"="#C19935",
    "GSAT"="#B3A033",
    "HSAT"="#A2A638",
    "LINE"="#8CAC3E",
    "Low_complexity"="#75B042",
    "LSAU"="#54B346",
    "LTR"="#51B756",
    "RC/Helitron"="#53BB73",
    "Retroposon"="#55BE8D",
    "RNA"="#54C0A5",
    "rRNA"="#52BEBB",
    "SAR"="#51BDCE",
    "Satellite/acro"="#4EB8DF",
    "Satellite/telo"="#53B0E3",
    "SATR1"="#5AA5DA",
    "scRNA"="#6B9AD2",
    "Simple_repeat"="#8992C8",
    "SINE"="#9A8AC1",
    "snRNA"="#A885BC",
    "srpRNA"="#B67EB6",
    "SST1"="#C378B2",
    "Satellite/subtelo"="#D173AF",
    "tRNA"="#ED72A5",
    "Unknown"="#EF768C", 
    "(GAATG)n"="#ff4000",
    "D20S16" = "#ffbf00", 
   "SATR2"= "#0080ff" )

defaultColor = "#000080"


    



rep_leg <- ggplot(data=repeats, mapping=aes(xmin=(X2),xmax=(X3),ymin=-1,ymax=1, fill = name))+
  geom_rect()  +  theme_void() +theme(legend.position="top") +labs(y="Axis")+xlim(cen1,cen2) +labs(y="Axis") + scale_fill_manual(values = repeatColors, drop = FALSE)+theme(legend.text=element_text(size=rel(1.5)))+theme(legend.title=element_blank())


plot_grid(rep_leg,plot, depth, ncol = 1, align="v")

```





