---
title: "`r title`"
output: pdf_document

---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(knitr)
library(tidyverse)
library(bsseq)
library(Biostrings)
library(GenomicRanges)
library(Rsamtools)
library(Sushi)

options(knitr.duplicate.label = 'allow')
```

## Methylation report for `r list.files[1]`

```{r include=FALSE}
freq <- read_tsv(files$summary[1])
mcalls <- read_tsv(files$summary[2])
bismark <- read_tsv(files$summary[3], col_names = F)
cov <- read_tsv(files$summary[4], col_names = F)

# parse files for the given roi
chr <- (str_split(roi, ":")[[1]])[1]
coord1 <- as.numeric(str_split((str_split(roi, ":")[[1]])[2], "-")[[1]][1])
coord2 <- as.numeric(str_split((str_split(roi, ":")[[1]])[2], "-")[[1]][2])


# calculate percent methylated and percent of high quality calls

m <- length(which(mcalls$log_lik_ratio>2.5))
u <- length(which(mcalls$log_lik_ratio<(-2.5)))
a <- length(mcalls$log_lik_ratio)

calls <- round((((m+u)/a)*100), digits = 2)
meth <- round(((m/(m+u))*100), digits=2)

```


Methylation Summary stats:
 
Percent high quality calls: `r calls`%  
Percent methylation: `r meth`%  


Histogram of log likelihood ratios

```{r}
print(ggplot(data = mcalls, aes(x=log_lik_ratio))+geom_histogram(alpha=.5, binwidth = .5, fill = "red")+theme_bw()+geom_vline(xintercept= c(-2.5, 2.5), linetype="dashed", color="black")+xlim(-25,25))

```


```{r include = FALSE}
mcalls_roi <- mcalls %>% 
  filter(chromosome == chr) %>%
  filter(start >= coord1) %>%
  filter(end <= coord2)

m <- length(which(mcalls_roi$log_lik_ratio>2.5))
u <- length(which(mcalls_roi$log_lik_ratio<(-2.5)))
a <- length(mcalls_roi$log_lik_ratio)

calls <- round((((m+u)/a)*100), digits = 2)
meth <- round(((m/(m+u))*100), digits=2)
```
Methylation Summary stats for `r roi`:
 
Percent high quality calls: `r calls`%  
Percent methylation: `r meth`%  

Histogram of log likelihood ratios in `r roi`
``` {r}
print(ggplot(data = mcalls_roi, aes(x=log_lik_ratio))+geom_histogram(alpha=.5, binwidth = .5, fill = "red")+theme_bw()+geom_vline(xintercept= c(-2.5, 2.5), linetype="dashed", color="black")+xlim(-25,25))

```
\newpage
Methylation frequency
```{r include = FALSE}
freq$pos <- rep("chrom", nrow(freq))
freq[freq$start >= coord1 & freq$end  <= coord2 , ][, "pos"] <- "cen"
```
``` {r}
print(ggplot(data = freq, aes(x = methylated_frequency, fill=freq$pos)) +geom_density(alpha=.5)+facet_wrap(~freq$pos, ncol=2)+theme_bw()+labs(x="methylated frequency (per base)", color="Position")+scale_fill_manual("region",values=c( "red", "green"))+theme(legend.position="bottom"))

```

``` {r}
print(binned <- freq %>%
  mutate(bin = ntile(start, (length(freq$start)/50))) %>%
  group_by(bin, pos) %>%
  summarise(avgmeth = mean(methylated_frequency)) %>%
  arrange(desc(avgmeth)) %>% ggplot(aes(x=avgmeth, fill = pos))+geom_density(alpha=.5)+theme_bw()+labs(x="Average methylation frequency (bin size 50bps)")+facet_wrap(~pos, ncol=2)+scale_fill_manual("Region",values=c( "red", "green")))
```

\newpage

```{r include = FALSE}
BS <- read.bismark(files$summary[3])
smooth <-BSmooth(BS, 
                 ns=smoothed)
cenx <- data.frame(start = coord1, end = coord2, chr = chr)
```

```{r}
plotRegion(smooth,cenx, addRegions=cenx, extend=wide, addTicks = F)


plotBedgraph((as.data.frame(cov)),chr,(coord1-wide),(coord2+wide), transparency =.5, color= SushiColors(2)(2)[1])

labelgenome("cen",coord1,coord2,n=3,scale="Kb")
mtext("Read Depth",side=2,line=1.75,cex=1,font=2)
axis(side=2,las=2,tcl=.2)
abline(v=c(coord1,coord2), col="black", lwd=1, lty=2)
#legend("topright",xpd=T, bty="n", inset=c(-5,0),legend=c("All ONT reads","ONT with high quality meth calls"), fill=opaque(SushiColors(2)(2)),border=SushiColors(2)(2),text.font=2,cex=1.0)

```