##Software to install
nanopolish: ${HOME}/nanopolish
f5c: ${HOME}/f5c-v0.5/f5c_x86_64_linux 
winnowmap: ${HOME}/Winnowmap-2.0/bin
nanopore-methylation-utilities: ${HOME}/nanopore-methylation-utilities
##References
#Must download
chm13-ref: ${HOME}/ref/chm13.draft_v1.0.fasta
hg002-ref: ${HOME}/ref/hg002.fasta
#out: /pym/Data/Nanopore/hg002_fast5 
#fastqdir: /pym/Data/Nanopore/hg002_fast5/fastq
#fast5: /pym/Data/Nanopore/hg002_fast5
#cores: 12
