##Software to install
nanopolish: $HOME/nanopolish
winnowmap: $HOME/Winnowmap-2.0/bin
nanopore-methylation-utilities: $HOME/nanopore-methylation-utilities
##References
#Must download
chm13-ref: &chm13 $HOME/ref/chm13.fasta
hg002-ref: $HOME/ref/HG002.fasta
ref: chm13-ref
base: /data
#out: /pym/Data/Nanopore/hg002_fast5 
#fastqdir: /pym/Data/Nanopore/hg002_fast5/fastq
#fast5: /pym/Data/Nanopore/hg002_fast5
#cores: 12
