workdir: /atium/Data/Nanopore/projects/210124_mason_bisulfite # path to save the analysis outputs
codedir: /home/gmoney/projects/chm13_meth/scripts/v1.0_final_assembly/bisulfite # path to this dir
reference: /kyber/Data/Nanopore/Analysis/gmoney/CHM13/v1.0_final_assembly/HG002/reference/reference.fasta # path to reference genome
threads: 60 # available cores
